trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

steps:
  - script: |
      docker --version 
      echo "Checking Docker Version"
    displayName: "Check Docker Version"

  - script: |
      sudo systemctl status docker
    displayName: "Check Docker Service Status"

  - script: |
      docker build -t helloworld:latest .
    displayName: "Docker Build Image"

  - script: |
      docker run helloworld:latest
    displayName: "Run Docker Container"

  - script: |
      docker ps -a
    displayName: "List Docker Containers"

  - script: |
      echo "checking node js version"
      node -v
      npm -v
    displayName: "Check Node JS Version"

  - script: |
      echo "checking java version"
      java --version
    displayName: "Check Java Version"

  - script: |
      echo "checking Go version"
      go version
    displayName: "Check Go Version"
  
  - script: |
      echo "checking dotnet version"
      dotnet --version
    displayName: "Check Dotnet Version"
