trigger:
  - main

pool:
  vmImage: "windows-latest"

steps:
  - script: |
      echo "checking node js version"
      node -v
      npm -v
    displayName: "Check Node JS Version"

  - script: |
      echo "checking java version"
      java --version
    displayName: "Check Java Version"

  - script: |
      echo "checking Go version"
      go version
    displayName: "Check Go Version"

  - script: |
      echo "checking dotnet version"
      dotnet --version
    displayName: "Check Dotnet Version"
